# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/msm8610-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter condor otus,$(TARGET_DEVICE)),)

endif
