# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/condor/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/condor

PRODUCT_COPY_FILES += \
    vendor/motorola/condor/proprietary/etc/acdbdata/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Bluetooth_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/General_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Global_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Handset_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Hdmi_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Headset_cal.acdb \
    vendor/motorola/condor/proprietary/etc/acdbdata/Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/acdbdata/Speaker_cal.acdb \
    vendor/motorola/condor/proprietary/etc/firmware/synaptics-s2316i-13101703-175833-condor.tdat:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/synaptics-s2316i-13101703-175833-condor.tdat \
    vendor/motorola/condor/proprietary/etc/firmware/synaptics-s2316t-13101703-175833-condor.tdat:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/synaptics-s2316t-13101703-175833-condor.tdat \
    vendor/motorola/condor/proprietary/lib/hw/camera.vendor.msm8610.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.msm8610.so \
    vendor/motorola/condor/proprietary/lib/libchromatix_ar0543_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_ar0543_common.so \
    vendor/motorola/condor/proprietary/lib/libchromatix_ar0543_default_video.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_ar0543_default_video.so \
    vendor/motorola/condor/proprietary/lib/libchromatix_ar0543_preview.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_ar0543_preview.so \
    vendor/motorola/condor/proprietary/lib/libchromatix_ar0543_snapshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_ar0543_snapshot.so \
    vendor/motorola/condor/proprietary/lib/libmmcamera_ar0543.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_ar0543.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_algorithm.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/motorola/condor/proprietary/vendor/lib/libmmcamera_tuning.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tuning.so \
    vendor/motorola/condor/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/motorola/condor/proprietary/vendor/lib/rfsa/adsp/libadsp_denoise_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libadsp_denoise_skel.so \
    vendor/motorola/condor/proprietary/vendor/lib/rfsa/adsp/libadsp_jpege_skel.so:$(TARGET_COPY_OUT_VENDOR)/lib/rfsa/adsp/libadsp_jpege_skel.so \
    vendor/motorola/condor/proprietary/vendor/lib/sensors.vendor.msm8610.so:$(TARGET_COPY_OUT_VENDOR)/lib/sensors.vendor.msm8610.so
